name: CI

on:
  push:
    branches: [ staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the 
    steps:
      - name: FTP copy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: 'sl1735.web.hostpoint.ch'
          ftp-username: 'lifiluzi'
          ftp-password: 'qZE-Xb5qpAd*cD4qV9Dq'
          local-dir: '~/www/lifiluzi.myhostpoint.ch/test'
