name: CI

on:
  push:
    branches: [ staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of th
    steps:
      - name: Deploy to production
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          command: 'ls -al'
          hosts: 'lifiluzi@greenwiperz.ch'
          privateKey: ${{ secrets.PRIVATE_KEY }}
          debug: true
          
