name: CI

on:
  push:
    branches: [ staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: FTP copy
        uses: GenieTim/ftp-action@v4.0.1
        with:
          host: 'sl1735.web.hostpoint.ch'
          user: 'lifiluzi'
          password: 'qZE-Xb5qpAd*cD4qV9Dq'
          remoteDir: '~/www/lifiluzi.myhostpoint.ch/test'
          
